### ISSUE TITLE
Logo SVG builder

### ISSUE THREAD

**Issue by Challier** [janczizikow/sleek#1]
Hey Jan,

First of all thanks for that template, it really looks amazing! I just started adapting it for my next data sciences blog.

I have a question : do you have an idea of how I can reproduce the svg on the left of the header (the one that says "sleek")? The font looks awesome and I'd like to keep the formatting that way, just a different text.

Cheers!
Victor

**Comment by janczizikow** [comment]
Hey @Challier !

Really glad that you like the template! The font used to make the svg is [718](http://www.terminaldesign.com/fonts/718-complete-family/). I used Demi Bold font weight and 18px as for the font size. Unfortunately, 718 isn't a free font, so you might want to purchase it or find a free font similar to it.

Cheers,
Jan

**Comment by Challier** [comment]
Hey Jan,

Sorry for the late answer, and thanks for your help. I'll probably find another font since I won't find any other use to buy this one.

Cheers,
Victor
