### ISSUE TITLE
Formspree form submission not working

### ISSUE THREAD

**Issue by lehmanwics** [janczizikow/sleek#15]
I have changed the formspree URL/email address as instructed but when I send now, I get the following error: 

```
Failed to load resource: the server responded with a status of 400 ()
```
It seems it is trying to submit to formspree.io/jan.czizikow@Fmail.com as that is the email in the error console but I don't see that anywhere in the project folder.

**Comment by janczizikow** [comment]
can you check `_js/scripts.js` and `_includes/form.js` files? the `<form>` tag should have an attribute of `action="https://formspree.io/{{site.email}}"`. And js it should be (bottom of js file):
```js
/*-------------------------------------------------------------------------*/
/* AJAX FORM SUBMIT */
/* -----------------------------------------------------------------------*/

$( "#contactForm" ).submit( function( e ) {

    e.preventDefault();
       // other variables
       var $url = $( "#contactForm" ).attr( "action" );

    $.ajax( {

        url: $url,
    // some more code down there
```

**Comment by kbeflo** [comment]
**npm start** seems to fix the problem, as the default email still persists on `assets/js/bundle.js`. 

@janczizikow, Formspree now prevents me from sending the form on a free verified account, I'm receiving:

 `{error: "To prevent spam, only Gold accounts may create AJAX forms."}`

**Comment by janczizikow** [comment]
hey @kbeflo I didn't know that formspree changed that. As you said will probably have to move away from AJAX. Shame 😞
