### ISSUE TITLE
Support for Tags and Categories

### ISSUE THREAD

**Issue by rahulpathakml** [janczizikow/sleek#17]
Hi Jan,

Can I ask you to add support for tags and categories in the theme.

Regards
Rahul

**Comment by janczizikow** [comment]
Hey @rahulpathakml yeah sure. I think there's a Jekyll plugin for that, but from what I remember Github pages don't allow it. Will have take a look  👍

**Comment by janczizikow** [comment]
You can now add `categories` to posts, which will appear on the post page and homepage.
