### ISSUE TITLE
White flash when browsing theme 

### ISSUE THREAD

**Issue by victorbjorklund** [janczizikow/sleek#19]
Hi! 

Thanks for a great theme. Not sure if this is a bug or something obvious that I missed. I changed the color of the menu from white to dark blue. Whenever I go to a new page in the site it flashes white for 0.3 sec before turning to the correct color. Tried with different browsers on different devices and I get the same result. Any idea how to fix it so that it doesn't always load the menu with a white flash (probably only noticeable then the menu is in another color than white)?

**Comment by janczizikow** [comment]
Hey @victorbjorklund, you can try running `gulp critical` (from the terminal in the directory of your project) to generate the [critical.css](https://www.smashingmagazine.com/2015/08/understanding-critical-css/#what-is-critical-css). Just make sure you're running a server before using the command. Most likely old styles are still inlined in html, which is causing the flash of color.

**Comment by janczizikow** [comment]
Gonna close this for now, feel free to open a new issue in case you still have the problem.
