### ISSUE TITLE
Page build warning?!

### ISSUE THREAD

**Issue by zorbathegreek** [janczizikow/sleek#2]
Hello, very nice looking site! 

I cloned and renamed it; next thing, I reveice a warning from <support@github.com>
> The page build completed successfully, but returned the following warning for the `gh-pages` branch:
You are attempting to use a Jekyll theme, "jekyll-sleek", which is not supported by GitHub Pages. Please visit https://pages.github.com/themes/ for a list of supported themes. If you are using the "theme" configuration variable for something other than a Jekyll theme, we recommend you rename this variable throughout your site. For more information, see https://help.github.com/articles/adding-a-jekyll-theme-to-your-github-pages-site/.
For information on troubleshooting Jekyll see:
  https://help.github.com/articles/troubleshooting-jekyll-builds
If you have any questions you can contact us by replying to this email. 

I changed to "master", same warning came in for that branch, too. 
What's wrong? I got the link from jekyllthemes.org!?
Thanks for shedding some light on me!

**Comment by janczizikow** [comment]
Hey @zorbathegreek !

If you want to deploy the theme to github pages **remove** the following line from `_config.yml`:

```yaml
theme: jekyll-sleek
```
I think this way the warning should disappear. Let me know if that worked for you!

**Comment by zorbathegreek** [comment]
Hello,
I removed that line and it worked. Though I am running it on master, not gh-pages. 
I am closing this issue.
Thanks!

**Comment by DanutaZabinska** [comment]
Hi,
I have the same problem, but after removing "theme: jekyll-sleek" the problem still exist and github do not want to build my project :( Could you help me?
I also tried to remove _site from gitignore file and send _site after local build, but also nothing.
