### ISSUE TITLE
How to generate the logos at bottom?

### ISSUE THREAD

**Issue by codeminion1** [janczizikow/sleek#20]
Just a question. How do I generate the mini icon at the bottom of the page? The twitter svg is what I am talking about. 

I want to make one for Reddit but not sure how you did it.

 Thanks

**Comment by janczizikow** [comment]
You mean how to create an svg or how to add the icon in the code?

If you need an svg: just google "reddit icon svg". first site that appeared in search results: [https://iconmonstr.com/reddit-4-svg/](https://iconmonstr.com/reddit-4-svg/)
Download the .svg file and you can open it with the text editor of your choice and copy the code. 

[More about SVG](https://www.w3schools.com/graphics/svg_intro.asp)

**Comment by codeminion1** [comment]
Thanks, didn't know how to do that
