### ISSUE TITLE
seo Liquid Exception

### ISSUE THREAD

**Issue by galpod** [janczizikow/sleek#21]
Hello,

I'm a beginner and trying to use the Sleek theme around my existing website. I copied all the relevant files into my repository but now when I run it I get this:

Liquid Exception: Liquid syntax error: Unknown tag 'seo' in _includes/head.html, included in _layouts/default.html

What am I missing? Any advice will be appreciated :)

Thanks!

**Comment by janczizikow** [comment]
Hey @galpod 

You're missing [jekyll-seo-gem](https://github.com/pmarsceill/jekyll-seo-gem). You can install it by running `gem install jekyll-seo` in the terminal in the directory of your project.

**Comment by janczizikow** [comment]
Or if you don't want to use the SEO plugin: just remove `{% seo %}` from `_includes/head.html`  (line 6).
