### ISSUE TITLE
question:github deployment

### ISSUE THREAD

**Issue by datadogmx** [janczizikow/sleek#28]
HI,

I have an issue when a try to deploy to github the routing doesnt work correctly, dou you have an example where you deploy to github?, thanks
![image](https://user-images.githubusercontent.com/9923159/41377645-5dea9038-6f22-11e8-913c-a3d350936898.png)

**Comment by datadogmx** [comment]
Also thank you for your great solution, is amazing, I am trying to start my personal blog and it looks very useful!

**Comment by janczizikow** [comment]
If you're deploying it as a personal project you should change the settings in `_config.yml`:

```yaml
baseurl: "" # the subpath of your site, e.g. /blog || Keep this as nothing if it's a personal page.
url: "https://datadogmx.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
```

I think that should do the trick, let me know if it helped.

**Comment by datadogmx** [comment]
Yes, this change has resolved everything.

Thanks!
