### ISSUE TITLE
Scaling of blogtitle area according to the title length

### ISSUE THREAD

**Issue by rahulpathakml** [janczizikow/sleek#5]
Hi Jan,

If the title length is large like in one of your demo article. title region overflows and some part of the article does not render properly.

![screenshot from 2018-02-11 12-30-16](https://user-images.githubusercontent.com/23165276/36070765-e742d8dc-0f27-11e8-9359-072f9185d5b5.png)

How can I avoid that from happening?

**Comment by janczizikow** [comment]
Hey @rahulpathakml,

Thanks, I'll have a look this week.

**Comment by rahulpathakml** [comment]
Thanks
