### ISSUE TITLE
Migrate to Gulp 4

### ISSUE THREAD

**Issue by janczizikow** [janczizikow/sleek#52]
Migrate from Gulp 3 to Gulp 4, update `gulpfile.js` to support the new syntax. It would be also great to switch to es6 syntax, by changing the filename to `gulpfile.babel.js`
Some resources found online:

## Migrating to gulp 4
[https://blog.wearewizards.io/migrating-to-gulp-4-by-example](https://blog.wearewizards.io/migrating-to-gulp-4-by-example)

## ES6 in gulp

[https://markgoodyear.com/2015/06/using-es6-with-gulp/](https://markgoodyear.com/2015/06/using-es6-with-gulp/)

**Comment by matheusportoo** [comment]
@janczizikow , can i help you with this issue?

**Comment by janczizikow** [comment]
@matheusportoo sure, that would be great

**Comment by lachieh** [comment]
@matheusportoo [¯\\\_(ツ)\_/¯ sorry!](https://media3.giphy.com/media/wdh1SvEn0E06I/giphy.gif?cid=3640f6095bc0ad4a4344422e45b1f14c)

**Comment by janczizikow** [comment]
Hey @matheusportoo sorry, @lachieh already fixed this, let me know if there's something else you would be interested in contributing, by just opening a new issue. For instance we could get rid of jQuery and just use ES6 with babel. Or add some further optimizations to `gulpfile`.
