### ISSUE TITLE
Help getting script to run

### ISSUE THREAD

**Issue by conorbarryhoke** [janczizikow/sleek#60]
Hello,

Absolutely gorgeous setup - I've been using this with a lot of success for my github.io page. 

I'd  like to add a some jquery .get script to one of the posts that will update some text on the post, but apparently there are some issues allowing cross origin requests for jquery.getJSON. Is there a way to cofigure this to be allowed?

**Comment by janczizikow** [comment]
Hey,

Not sure. Most likely your site isn't allowed to get the data from the server. You should check the server setup / API documentation from where you want to fetch the data
