### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by jamugha** [janczizikow/sleek#64]
Hi,

Do you plan to add any multilingual support for this theme?

**Comment by janczizikow** [comment]
Hey @h4ckd0wn not really. I would bet my bottom dollar that there're some jekyll plugins for this.

**Comment by h4ckd0wn** [comment]
Yeah but they're sometimes hard to implement

Also, what is the correct size for the svg logo?

**Comment by investmentiq** [comment]
Reviving an old thread anyone done internationalization for this theme? I am working on one with the  [jekyll-multiple-languages-plugin](https://github.com/kurtsson/jekyll-multiple-languages-plugin) but running into some issues.
